org: meshu
app: contact-form
service: contact-form

frameworkVersion: '3'

provider:
  name: aws
  region: eu-west-2
  runtime: nodejs14.x

functions:
  sendMessage:
    handler: handler.sendMessage
    events:
      - http:
          method: post
          path: /
          cors: true
